### ISSUE TITLE
Need help testing.

### ISSUE THREAD

**Issue by neato82** [AlejandroMS1912/TwitterBot-without-API#2]
Hello,

Thanks for making this.
I am trying to get this running on my end but encountered a couple issues.

Where I try to run "pip install random" I get this:

`ERROR: Could not find a version that satisfies the requirement random (from versions: none)
ERROR: No matching distribution found for random
WARNING: You are using pip version 20.2.3; however, version 22.3.1 is available.
You should consider upgrading via the 'c:\python38\python.exe -m pip install --upgrade pip' command.`

And then when I try to run "Like.py" I get this:

`C:\Users\William Salas\Downloads\_APPZ\TwitterBot-without-API-main>Like.py
Select your index (hashtag or username): hashtag
Type the hashtag: test
C:\Users\William Salas\Downloads\_APPZ\TwitterBot-without-API-main\Like.py:32: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  self.bot = webdriver.Chrome(executable_path='C:/Users/William Salas/Downloads/_APPZ/TwitterBot-without-API-main/chromedriver.exe') # Copy YOUR chromedriver path

DevTools listening on ws://127.0.0.1:54621/devtools/browser/93f4c6d1-ee58-4368-8ada-ef5ae6635cf9
[3932:27840:1118/121104.937:ERROR:device_event_log_impl.cc(215)] [12:11:04.938] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
Traceback (most recent call last):
  File "C:\Users\William Salas\Downloads\_APPZ\TwitterBot-without-API-main\Like.py", line 129, in <module>
    UserParameters.where_to_like(inputVariable, user, hashtag)
  File "C:\Users\William Salas\Downloads\_APPZ\TwitterBot-without-API-main\Like.py", line 116, in where_to_like
    RejectCookies = bot.find_element("xpath", '//*[@id="layers"]/div/div/div/div/div/div[2]/div[2]/div/span/span')   
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1244, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="layers"]/div/div/div/div/div/div[2]/div[2]/div/span/span"}
  (Session info: chrome=107.0.5304.107)
Stacktrace:
Backtrace:
        Ordinal0 [0x00541ED3+2236115]
        Ordinal0 [0x004D92F1+1807089]
        Ordinal0 [0x003E66FD+812797]
        Ordinal0 [0x004155DF+1005023]
        Ordinal0 [0x004157CB+1005515]
        Ordinal0 [0x00447632+1209906]
        Ordinal0 [0x00431AD4+1120980]
        Ordinal0 [0x004459E2+1202658]
        Ordinal0 [0x004318A6+1120422]
        Ordinal0 [0x0040A73D+960317]
        Ordinal0 [0x0040B71F+964383]
        GetHandleVerifier [0x007EE7E2+2743074]
        GetHandleVerifier [0x007E08D4+2685972]
        GetHandleVerifier [0x005D2BAA+532202]
        GetHandleVerifier [0x005D1990+527568]
        Ordinal0 [0x004E080C+1837068]
        Ordinal0 [0x004E4CD8+1854680]
        Ordinal0 [0x004E4DC5+1854917]
        Ordinal0 [0x004EED64+1895780]
        BaseThreadInitThunk [0x76C4FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x77867BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77867B8E+238]

C:\Users\William Salas\Downloads\_APPZ\TwitterBot-without-API-main>`

Do you know what I might be doing wrong?

Thanks!

**Comment by AlejandroMS1912** [comment]
Hi men, thanks for the comment.
The first error (DeprecationWarning)  is not a problem to execute the script without issues.
In relation to the pip intsall try "pip install random2" (https://pypi.org/project/random2/) and if you have entered your Twitter username and password and your chromedriver path correctly (You can check this video as an example: https://www.youtube.com/watch?v=XoR1Ak_FxAA&t=1s ) it should work without problems.

**Comment by AlejandroMS1912** [comment]
It seems that the "RejectCookies" button generated some conflicts, I have implemented a exception and if you download the new code it should works. 

Again, thank you very much for helping to catch these errors.
